/**
 * Generates a candidate-safe PDF version of the recruiter brief.
 * Strips recruiter-only sections (Communication Guidance, Be Ready to Answer).
 */
import { jsPDF } from "jspdf";
import type { RecruiterBriefData } from "./generateRecruiterBrief";

const MARGIN = 20;
const PAGE_W = 210;
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H = 6;
const SECTION_GAP = 10;

function addPageIfNeeded(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 275) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function drawSectionHeader(doc: jsPDF, y: number, title: string): number {
  y = addPageIfNeeded(doc, y, 14);
  doc.setFillColor(30, 30, 42);
  doc.rect(MARGIN, y, CONTENT_W, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(200, 180, 120);
  doc.text(title.toUpperCase(), MARGIN + 4, y + 5.5);
  return y + 12;
}

function drawBullets(doc: jsPDF, y: number, items: string[], prefix = "›"): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 70);
  for (const item of items) {
    const lines = doc.splitTextToSize(`${prefix} ${item}`, CONTENT_W - 8);
    y = addPageIfNeeded(doc, y, lines.length * LINE_H);
    doc.text(lines, MARGIN + 4, y + 4);
    y += lines.length * LINE_H + 1;
  }
  return y;
}

export function generateCandidatePdf(brief: RecruiterBriefData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // ── HEADER ──
  doc.setFillColor(18, 18, 28);
  doc.rect(0, 0, PAGE_W, 45, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(brief.companyName, MARGIN, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(180, 180, 190);
  doc.text(`${brief.industry}  ·  Career Intelligence Score: ${brief.score}/100  ·  ${brief.confidence} Confidence`, MARGIN, 32);

  doc.setFontSize(7);
  doc.setTextColor(140, 140, 150);
  doc.text("Candidate Intelligence Brief  ·  Generated by Who Do I Work For?  ·  wdiwf.jackyeclayton.com", MARGIN, 40);

  let y = 52;

  // ── WHAT'S SHOWING UP ──
  y = drawSectionHeader(doc, y, "What's Showing Up");
  for (const s of brief.signals) {
    const indicator = s.level === "positive" ? "✓" : s.level === "caution" ? "⚠" : "–";
    const lines = doc.splitTextToSize(`${indicator}  ${s.label}: ${s.detail}`, CONTENT_W - 8);
    y = addPageIfNeeded(doc, y, lines.length * LINE_H + 2);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(s.level === "caution" ? 180 : 60, s.level === "positive" ? 140 : 60, s.level === "caution" ? 50 : 70);
    doc.text(lines, MARGIN + 4, y + 4);
    y += lines.length * LINE_H + 2;
  }
  y += SECTION_GAP;

  // ── WHAT THIS SUGGESTS ──
  y = drawSectionHeader(doc, y, "What This Suggests");
  y = drawBullets(doc, y, brief.patterns);
  y += SECTION_GAP;

  // ── CANDIDATE PERSPECTIVE ──
  y = drawSectionHeader(doc, y, "Questions Worth Asking");
  y = drawBullets(doc, y, brief.candidateQuestions, "?");
  y += 4;
  if (brief.candidateConcerns.length > 0 && brief.candidateConcerns[0] !== "Standard due-diligence questions — nothing elevated") {
    y = addPageIfNeeded(doc, y, 10);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(160, 130, 70);
    doc.text("AREAS TO DIG INTO", MARGIN + 4, y + 4);
    y += 8;
    y = drawBullets(doc, y, brief.candidateConcerns, "·");
  }
  y += SECTION_GAP;

  // ── TRADEOFFS ──
  y = drawSectionHeader(doc, y, "What the Record Shows");
  y = addPageIfNeeded(doc, y, 10);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(80, 160, 100);
  doc.text("STRENGTHS", MARGIN + 4, y + 4);
  y += 8;
  y = drawBullets(doc, y, brief.strengths, "+");
  y += 4;
  y = addPageIfNeeded(doc, y, 10);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(200, 160, 60);
  doc.text("WORTH KNOWING", MARGIN + 4, y + 4);
  y += 8;
  y = drawBullets(doc, y, brief.honestAbout, "–");
  y += SECTION_GAP;

  // ── FOOTER ──
  y = addPageIfNeeded(doc, y, 20);
  doc.setDrawColor(200, 180, 120);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 130);
  doc.text("Stop applying. Start aligning.", MARGIN, y + 3);
  doc.text("wdiwf.jackyeclayton.com", PAGE_W - MARGIN, y + 3, { align: "right" });

  const filename = `${brief.companyName.replace(/[^a-zA-Z0-9]/g, "-")}-candidate-brief.pdf`;
  doc.save(filename);
}
