import { useState } from "react";
import { Share2, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { toast } from "sonner";

interface PrepPackExportProps {
  content: string;
  companyName: string;
}

export function PrepPackExport({ content, companyName }: PrepPackExportProps) {
  const [copied, setCopied] = useState(false);

  const getCleanContent = () => {
    // Strip any pricing/product language, keep just the prep content
    const lines = content.split("\n");
    const cleanLines = lines.filter(line => {
      const lower = line.toLowerCase();
      return !lower.includes("upgrade") && !lower.includes("pricing") && !lower.includes("subscribe");
    });
    return `Interview Prep Brief: ${companyName}\nGenerated by WDIWF Intelligence Engine\n${"-".repeat(40)}\n\n${cleanLines.join("\n")}`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(getCleanContent());
      setCopied(true);
      toast.success("Prep pack copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  };

  const handlePrint = () => {
    const printContent = getCleanContent();
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast.error("Please allow popups to print");
      return;
    }
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Interview Prep: ${companyName}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 40px auto; padding: 20px; color: #1a1a1a; line-height: 1.6; }
          h1 { font-size: 20px; border-bottom: 2px solid #111; padding-bottom: 8px; }
          h2 { font-size: 16px; margin-top: 24px; color: #333; }
          ul, ol { padding-left: 20px; }
          li { margin-bottom: 6px; }
          strong { color: #000; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 12px; color: #888; }
        </style>
      </head>
      <body>
        <h1>Interview Prep: ${companyName}</h1>
        ${content.replace(/## /g, "<h2>").replace(/\n/g, "<br>")}
        <div class="footer">Generated by WDIWF Intelligence Engine. Based on public records, not opinion.</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="sm" className="gap-1 text-xs h-7">
          <Share2 className="w-3 h-3" />
          Forward
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handleCopy}>
          {copied ? <Check className="w-3.5 h-3.5 mr-2" /> : <Copy className="w-3.5 h-3.5 mr-2" />}
          {copied ? "Copied!" : "Copy to clipboard"}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handlePrint}>
          <Share2 className="w-3.5 h-3.5 mr-2" />
          Print / Save as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
