export interface PaletteEntry {
  id: string;
  name: string;
  mood: string;
  bg: string;
  accent: string;
  dark: string;
  text: string;
  sub: string;
  description: string;
  inspiration?: string;
}

export const MOOD_FILTERS = [
  { value: "all", label: "ALL" },
  { value: "maison", label: "MAISON" },
  { value: "editorial", label: "EDITORIAL" },
  { value: "bold", label: "BOLD" },
  { value: "moody", label: "MOODY" },
  { value: "warm", label: "WARM" },
  { value: "neon", label: "NEON" },
  { value: "classic", label: "CLASSIC" },
];

export const PALETTES: PaletteEntry[] = [
  {
    id: "rosso",
    name: "Rosso",
    mood: "maison",
    bg: "#1A0508",
    accent: "#BE0B2B",
    dark: "#0D0204",
    text: "#FFF5F0",
    sub: "#D4808A",
    description: "Power red. The kind that stops rooms and starts conversations.",
    inspiration: "The color that needs no introduction.",
  },
  {
    id: "midnight-gold",
    name: "Midnight Gold",
    mood: "classic",
    bg: "#0A0A0E",
    accent: "#F0C040",
    dark: "#050508",
    text: "#F0EBE0",
    sub: "#7A7590",
    description: "The original. Dark authority with gold conviction.",
  },
  {
    id: "ivory-noir",
    name: "Ivory Noir",
    mood: "maison",
    bg: "#FAF7F2",
    accent: "#1A1A1A",
    dark: "#F0EDE6",
    text: "#0A0A0A",
    sub: "#6B6560",
    description: "Whisper-quiet luxury. Ivory pages, black ink, nothing wasted.",
    inspiration: "Atelier precision.",
  },
  {
    id: "blood-ivory",
    name: "Blood & Ivory",
    mood: "bold",
    bg: "#1A0000",
    accent: "#FF2D2D",
    dark: "#0D0000",
    text: "#FFF5F5",
    sub: "#FF9090",
    description: "Urgent. Unapologetic. For stories that demand attention.",
  },
  {
    id: "poudre",
    name: "Poudre",
    mood: "maison",
    bg: "#1C1418",
    accent: "#D4A0B0",
    dark: "#0E0A0C",
    text: "#F8F0F0",
    sub: "#B88898",
    description: "Blush on black. Softness as a power move.",
    inspiration: "Runway afterglow.",
  },
  {
    id: "deep-emerald",
    name: "Deep Emerald",
    mood: "editorial",
    bg: "#021A12",
    accent: "#34D399",
    dark: "#010D09",
    text: "#E0FFF0",
    sub: "#6BDFB8",
    description: "Money trails and pay equity. Follow the green.",
  },
  {
    id: "electric-violet",
    name: "Electric Violet",
    mood: "neon",
    bg: "#0C0020",
    accent: "#A855F7",
    dark: "#060010",
    text: "#F0E8FF",
    sub: "#C084FC",
    description: "Future of work energy. Disruption in purple.",
  },
  {
    id: "burnt-sienna",
    name: "Burnt Sienna",
    mood: "warm",
    bg: "#1A0E08",
    accent: "#E8723A",
    dark: "#0D0704",
    text: "#FFF0E6",
    sub: "#D4956E",
    description: "Warm conviction. For organizing and solidarity stories.",
  },
  {
    id: "ice-steel",
    name: "Ice & Steel",
    mood: "editorial",
    bg: "#08101A",
    accent: "#60A5FA",
    dark: "#040810",
    text: "#E0EEFF",
    sub: "#8BB8E8",
    description: "Cool precision. Regulation and policy analysis.",
  },
  {
    id: "noir-rose",
    name: "Noir Rosé",
    mood: "moody",
    bg: "#12080E",
    accent: "#F472B6",
    dark: "#090405",
    text: "#FFE8F0",
    sub: "#E0A0BF",
    description: "Dark glamour. Worker rights deserve to look this good.",
  },
  {
    id: "sulfur-black",
    name: "Sulfur Black",
    mood: "bold",
    bg: "#0E0E00",
    accent: "#FACC15",
    dark: "#070700",
    text: "#FFFFF0",
    sub: "#D4C060",
    description: "Warning signs. Caution tape energy for layoff coverage.",
  },
  {
    id: "phantom-teal",
    name: "Phantom Teal",
    mood: "moody",
    bg: "#041418",
    accent: "#2DD4BF",
    dark: "#020A0C",
    text: "#E0FFFA",
    sub: "#70C8B8",
    description: "Ghost jobs and hidden policies. The phantom receipt.",
  },
  {
    id: "white-hot",
    name: "White Hot",
    mood: "neon",
    bg: "#FFFFFF",
    accent: "#FF0055",
    dark: "#F5F5F5",
    text: "#0A0A0A",
    sub: "#555555",
    description: "Inverted. Loud. For when the story is too big to whisper.",
  },
  {
    id: "slate-copper",
    name: "Slate & Copper",
    mood: "classic",
    bg: "#14161C",
    accent: "#D97706",
    dark: "#0A0B0E",
    text: "#E8E4DC",
    sub: "#8E8578",
    description: "Investigative warmth. Old-school journalism meets new receipts.",
  },
  {
    id: "cyber-lime",
    name: "Cyber Lime",
    mood: "neon",
    bg: "#050A00",
    accent: "#84CC16",
    dark: "#030500",
    text: "#F0FFE0",
    sub: "#A0C850",
    description: "AI workplace signals. Digital-native energy.",
  },
  {
    id: "champagne-noir",
    name: "Champagne Noir",
    mood: "editorial",
    bg: "#1A1814",
    accent: "#D4C090",
    dark: "#0D0C0A",
    text: "#F0EDE4",
    sub: "#A09878",
    description: "Quiet luxury. When the receipt speaks for itself.",
  },
  {
    id: "bruise-purple",
    name: "Bruise",
    mood: "moody",
    bg: "#10081A",
    accent: "#7C3AED",
    dark: "#080410",
    text: "#E8E0FF",
    sub: "#9070C0",
    description: "Dark as a policy reversal. For DEI rollback coverage.",
  },
  {
    id: "sunrise-coral",
    name: "Sunrise Coral",
    mood: "warm",
    bg: "#1A100E",
    accent: "#F97316",
    dark: "#0D0807",
    text: "#FFF0E8",
    sub: "#D4906E",
    description: "New day energy. Worker wins and organizing victories.",
  },
  {
    id: "arctic-white",
    name: "Arctic",
    mood: "classic",
    bg: "#F0F2F5",
    accent: "#1E293B",
    dark: "#E4E6EA",
    text: "#0F172A",
    sub: "#64748B",
    description: "Clean. Clinical. When the data should do the talking.",
  },
];
